# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'TestTaskFlickr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestTaskFlickr
pod 'FlickrKit', '~> 1.0.9'

end
